# fly.toml app configuration file generated for tanghamcuamayconmeo on 2026-05-17T11:21:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tanghamcuamayconmeo'
primary_region = 'sin'

[build]

[[vm]]
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 1
  memory_mb = 2048
  size = 'performance-cpu-1x'
